apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: incident-analysis
  labels:
    app: main-app
    component: orchestrator
    app.kubernetes.io/part-of: incident-analysis
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
        component: orchestrator
    spec:
      serviceAccountName: incident-analysis-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: main-app
        image: your-registry/incident-analysis-main:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "info"
        - name: GRAFANA_MCP_URL
          valueFrom:
            configMapKeyRef:
              name: main-app-config
              key: grafana_mcp_url
        - name: OPSGENIE_MCP_URL
          valueFrom:
            configMapKeyRef:
              name: main-app-config
              key: opsgenie_mcp_url
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-secret
              key: api_key
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30