apiVersion: v1
kind: Service
metadata:
  name: main-app-service
  namespace: incident-analysis
  labels:
    app: main-app
    component: orchestrator
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: main-app